#!/usr/bin/env bash

set -e

packages=(curl ca-certificates git)
tempdir=$(mktemp -d)

apt-get update -qq
apt-get install -qqy ${packages[@]}

mkdir -p /etc/profile.d


pushd $tempdir
    echo "Retrieving and installing functions $CONTAINER_UTILS_VERSION ..."
    git clone -b $CONTAINER_UTILS_VERSION --depth 1 \
        https://github.com/$GITHUB_ORG/container-utils && \
        mv container-utils/functions/* /etc/profile.d/

    popd && rm -rf $tempdir

dircolors -p > /etc/dircolors

apt-get purge -y --auto-remove ${packages[@]}
apt-clean --aggressive
