#!/usr/bin/env bash

set -e

packages=(curl ca-certificates git upx-ucl)
tempdir=$(mktemp -d)

apt-get update -qq
apt-get install -qqy ${packages[@]}

mkdir -p /usr/local/bin

pushd $tempdir
    # sha256sum --check <(curl -sSL https://github.com/Yelp/dumb-init/releases/download/v${DUMB_INIT_VERSION}/sha256sums | tail -n -1) --status && \
    echo "Retrieving, verifying, packing, and installing dumb-init $DUMB_INIT_VERSION ..."
    curl -sSL -O \
        https://github.com/Yelp/dumb-init/releases/download/v${DUMB_INIT_VERSION}/dumb-init_${DUMB_INIT_VERSION}_amd64 && \
        chmod +x dumb-init* && \
        upx --ultra-brute -9 dumb-init* && \
        mv dumb-init* /dumb-init

    # sha256sum --check <(curl -sSL https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/SHA256SUMS | head -1) --status && \
    # gpg --no-tty --verify <(curl -sSL ${GOSU_DOWNLOAD_URL}.asc) gosu-amd64 && \

    echo "Retrieving, verifying, packing, and installing gosu $GOSU_VERSION ..."
    GOSU_DOWNLOAD_URL=https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64
    # gpg --keyserver pool.sks-keyservers.net --recv-key BF357DD4
    curl -sSL -O $GOSU_DOWNLOAD_URL && \
        chmod +x gosu-* && \
        upx --ultra-brute -9 gosu-* && \
        mv gosu-* /usr/local/bin/gosu

    echo "Retrieving, packing, and installing goss $GOSS_VERSION ..."
    curl -sSL -O https://github.com/aelsabbahy/goss/releases/download/v${GOSS_VERSION}/goss-linux-amd64 && \
        chmod +x goss-* && \
        upx --ultra-brute -9 goss-* && \
        mv goss-* /usr/local/bin/goss && \
        mkdir -p /etc/goss

    echo "Retrieving and installing scripts $CONTAINER_UTILS_VERSION ..."
    git clone -b $CONTAINER_UTILS_VERSION --depth 1 \
        https://github.com/joeblackwaslike/container-utils && \
        chmod +x container-utils/scripts/* && \
        cp container-utils/scripts/* /usr/local/bin/

    popd && rm -rf $tempdir

apt-get purge -y --auto-remove ${packages[@]}
apt-clean --aggressive
