#!/usr/bin/env bash

set -e

packages=(curl ca-certificates)
tempdir=$(mktemp -d)

apt-get update -qq
apt-get install -qqy ${packages[@]}

mkdir -p /usr/local/lib

pushd $tempdir
    echo "Retrieving, verifying, packing, and installing liboverridehostname $LIBOVERRIDEHOSTNAME_VERSION ..."
    curl -sSL -O \
        https://github.com/$GITHUB_USER/overridehostname/releases/download/$LIBOVERRIDEHOSTNAME_VERSION/liboverridehostname.so.1 && \
        grep -qv 'Not Found' liboverridehostname.so.1 && \
        mv liboverridehostname.so* /usr/local/lib/

    popd && rm -rf $tempdir

apt-get purge -y --auto-remove ${packages[@]}
apt-clean --aggressive
