#!/usr/binenv bash

set -e

tempdir=$(mktemp -d)

mkdir -p /usr/local/lib

pushd $tempdir
    echo "Retrieving, verifying, packing, and installing dumb-init ..."
    curl -sSL -O \
        https://github.com/joeblackwaslike/overridehostname/releases/download/$LIBOVERRIDEHOSTNAME_VERSION/liboverridehostname.so.1 && \
        mv liboverridehostname.so* /usr/local/lib/

    popd && rm -rf $tempdir
