#!/bin/bash -e

PARENT=$(dirname $(dirname $(realpath $0)))
VERSION_FILE=$PARENT/versions.env

: ${RELEASE:=debian/jessie}
export RELEASE

CODENAME=$(basename $RELEASE)
BASEDIR=/turnkey/tklx/base
echo $1 | grep -q ^chanko && WORKDIR=$BASEDIR/builder/chankos/$CODENAME

# echo -e "
# docker run -it --rm --privileged \
#     -e RELEASE \
#     $([[ -a $VERSION_FILE ]] && echo \"--env-file=$VERSION_FILE\") \
#     -e PKGCACHE=$BASEDIR/builder/chankos/$CODENAME/archives \
#     -e CDPATH=.:/turnkey/fab:/turnkey \
#     -v $PARENT:$BASEDIR \
#     -w ${WORKDIR:-$BASEDIR} \
#     builder $@
# "

docker run -it --rm --privileged \
    -e RELEASE \
    $([[ -a $VERSION_FILE ]] && echo "--env-file=$VERSION_FILE") \
    -e PKGCACHE=$BASEDIR/builder/chankos/$CODENAME/archives \
    -e CDPATH=.:/turnkey/fab:/turnkey \
    -v $PARENT:$BASEDIR \
    -w ${WORKDIR:-$BASEDIR} \
    builder $@
