#!/bin/bash -e

base=$(dirname $0)

VERSION_FILE=$base/../versions.env
[[ -a $VERSION_FILE ]] && . $VERSION_FILE

: ${RELEASE:=debian/jessie}

CODENAME=$(basename $RELEASE)
BASEDIR=/turnkey/tklx/base

echo $1 | grep -q ^chanko && WORKDIR=$BASEDIR/builder/chankos/$CODENAME


echo -e "
docker run -it --rm --privileged \
    -e RELEASE \
    $([[ -a $VERSION_FILE ]] && echo \"--env-file $VERSION_FILE\") \
    -e PKGCACHE=$WORKDIR/archives \
    -e CDPATH=.:/turnkey/fab:/turnkey \
    -v $(dirname $(dirname $(realpath $0))):$BASEDIR \
    -w ${WORKDIR:-$BASEDIR} \
    deb-builder \"$@\"
"

docker run -it --rm --privileged \
    -e RELEASE \
    $([[ -a $VERSION_FILE ]] && echo "--env-file $VERSION_FILE") \
    -e PKGCACHE=$WORKDIR/archives \
    -e CDPATH=.:/turnkey/fab:/turnkey \
    -v $(dirname $(dirname $(realpath $0))):$BASEDIR \
    -w ${WORKDIR:-$BASEDIR} \
    deb-builder "$@"
